const TG=window.Telegram?.WebApp;TG?.ready();TG?.expand();if(TG){TG.setHeaderColor?.("#fff9fa");TG.setBackgroundColor?.("#f9eef1");TG.setBottomBarColor?.("#fff9fa")}
const SUPABASE_URL="https://agvkksymvwsmrcxpjhts.supabase.co";const SUPABASE_KEY="sb_publishable_IaNqi5idKSJYHqfWWA9AGA_FDyyJaFu";const API=SUPABASE_URL+"/functions/v1/miniapp-api";const user=TG?.initDataUnsafe?.user||{};const initData=TG?.initData||"";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const screens=$$(".screen"), nav=$$(".bottom-nav button");
function go(id){screens.forEach(x=>x.classList.toggle("active",x.id===id));nav.forEach(x=>x.classList.toggle("active",x.dataset.screen===id));window.scrollTo({top:0,behavior:"smooth"});if(id==="mybooking")loadBooking("bookingBox");if(id==="cancel")loadBooking("cancelBox",true);if(id==="reschedule")loadBooking("rescheduleBox",false,true)}
$$('[data-screen]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.screen)));$$('.back').forEach(b=>b.addEventListener('click',()=>go('home')));$('#closeBtn').onclick=()=>TG?.close?.();
$('#adminBtn').onclick=()=>{if(TG?.openTelegramLink)TG.openTelegramLink('https://t.me/olkadolka228');else location.href='https://t.me/olkadolka228'};
$('#name').value=[user.first_name,user.last_name].filter(Boolean).join(' ');$('#date').min=new Date().toISOString().slice(0,10);
async function api(action,extra={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY},body:JSON.stringify({action,initData,...extra})});let d=null;try{d=await r.json()}catch{}if(!r.ok||!d?.ok)throw new Error(d?.error||'Ошибка сервера');return d}
function esc(v){return String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function bookingHtml(b){if(!b)return '<div class="loader">❌ Активная запись не найдена.</div>';const date=String(b.booking_date||'').split('-').reverse().join('.');return `<div class="booking-details"><div class="detail"><span>👤 Имя</span><b>${esc(b.name)}</b></div><div class="detail"><span>📅 Дата</span><b>${esc(date)}</b></div><div class="detail"><span>🕐 Время</span><b>${esc(String(b.booking_time||'16:00').slice(0,5))}</b></div><div class="detail"><span>💅 Длина</span><b>${esc(b.nail_length)}</b></div><div class="detail"><span>🎨 Дизайн</span><b>${esc(b.design||'нет')}</b></div><div class="detail"><span>✂️ Снятие</span><b>${b.removal?'да':'нет'}</b></div><div class="detail"><span>🔧 Коррекция</span><b>${b.correction?'да':'нет'}</b></div><div class="detail"><span>💬 Комментарий</span><b>${esc(b.comment||'нет')}</b></div></div>`}
async function loadBooking(boxId,cancelMode=false,rescheduleMode=false){const box=$('#'+boxId);box.innerHTML='<div class="loader">Загрузка…</div>';try{const d=await api('get_booking');if(!d.booking){box.innerHTML='<div class="loader">❌ Активная запись не найдена.</div>';return}box.innerHTML=bookingHtml(d.booking)+(cancelMode?'<div class="actions"><button class="danger-btn" id="doCancel">❌ Отменить запись</button><button class="secondary" id="backHome">Назад</button></div>':rescheduleMode?'<div class="actions"><button class="primary" id="toReschedule" style="grid-column:1/-1">📅 Выбрать новую дату</button></div>':'<div class="actions"><button class="secondary" id="toCancel">❌ Отменить</button><button class="secondary" id="toReschedule">🔄 Перенести</button></div>');$('#backHome')?.addEventListener('click',()=>go('home'));$('#toCancel')?.addEventListener('click',()=>go('cancel'));$('#toReschedule')?.addEventListener('click',()=>{document.getElementById('rescheduleDate')?.focus();});$('#doCancel')?.addEventListener('click',cancelBooking);if(rescheduleMode)renderReschedule(box,d.booking)}catch(e){box.innerHTML=`<div class="loader">❌ ${esc(e.message)}</div>`}}
async function cancelBooking(){if(!confirm('Отменить вашу запись?'))return;try{await api('cancel_booking');toast('Запись отменена');go('home')}catch(e){toast(e.message,true)}}
function renderReschedule(box,b){box.innerHTML=bookingHtml(b)+`<div class="form-card" style="margin-top:14px"><label>Новая дата<input id="rescheduleDate" type="date"></label><div class="fixed-time">🕐 Время останется <b>16:00</b></div><button class="primary wide" id="doReschedule">🔄 Перенести запись</button><div id="resStatus" class="status"></div></div>`;const input=$('#rescheduleDate');input.min=new Date().toISOString().slice(0,10);$('#doReschedule').onclick=async()=>{const date=input.value;if(!date){$('#resStatus').textContent='Выберите дату';return}const day=new Date(date+'T00:00:00').getDay();if(day===0||day===6){$('#resStatus').textContent='Можно выбрать только будний день';return}try{await api('reschedule_booking',{newDate:date});toast('Запись перенесена');go('mybooking')}catch(e){$('#resStatus').textContent=e.message;$('#resStatus').className='status error'}}}
async function submitBooking(){const status=$('#bookingStatus');const date=$('#date').value;if(!$('#name').value.trim()||!date){status.textContent='Заполните имя и дату';status.className='status error';return}const day=new Date(date+'T00:00:00').getDay();if(day===0||day===6){status.textContent='Можно выбрать только будний день';status.className='status error';return}const btn=$('#submitBooking');btn.disabled=true;btn.textContent='Сохраняем…';try{await fetch(SUPABASE_URL+'/functions/v1/send-booking-telegram',{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY},body:JSON.stringify({name:$('#name').value.trim(),telegram_username:user.username?('@'+user.username):'',telegram_chat_id:user.id||null,booking_date:date,booking_time:'16:00',nail_length:$('#length').value,design:$('#design').value.trim(),removal:$('#removal').checked,correction:$('#correction').checked,comment:$('#comment').value.trim()})}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw new Error(d.error||'Не удалось сохранить бронь')});status.textContent='Запись успешно создана 💗';status.className='status ok';toast('Запись подтверждена');setTimeout(()=>go('mybooking'),500)}catch(e){status.textContent=e.message;status.className='status error'}finally{btn.disabled=false;btn.textContent='Подтвердить запись'}}
$('#submitBooking').onclick=submitBooking;
function toast(t,error=false){const x=$('#toast');x.textContent=t;x.style.background=error?'#9d5366':'#3b2d32';x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
