const TG=window.Telegram?.WebApp;TG?.ready();TG?.expand();if(TG){TG.setHeaderColor?.('#fff7f8');TG.setBackgroundColor?.('#fff7f8');TG.setBottomBarColor?.('#fff7f8')}
const SUPABASE_URL='https://agvkksymvwsmrcxpjhts.supabase.co';
const SUPABASE_KEY='sb_publishable_IaNqi5idKSJYHqfWWA9AGA_FDyyJaFu';
const API=SUPABASE_URL+'/functions/v1/miniapp-api';
const user=TG?.initDataUnsafe?.user||{};const initData=TG?.initData||'';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const screens=$$('.screen'),nav=$$('.bottom-nav button');
const state={booked:new Set(),month:new Date(new Date().getFullYear(),new Date().getMonth(),1),selected:null,file:null,fileData:null};
function esc(v){return String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function fmtDate(v){return String(v||'').split('-').reverse().join('.')}
function localISO(d=new Date()){const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)}
function go(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));nav.forEach(b=>b.classList.toggle('active',b.dataset.screen===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='booking'){loadAvailability().catch(()=>{});renderCalendar()}if(id==='mybooking')loadBooking('bookingBox');if(id==='cancel')loadBooking('cancelBox',true,false);if(id==='reschedule')loadBooking('rescheduleBox',false,true)}
$$('[data-screen]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.screen)));$$('.back').forEach(b=>b.addEventListener('click',()=>go('home')));$('#closeBtn')?.addEventListener('click',()=>TG?.close?.());
$('#adminBtn')?.addEventListener('click',()=>{const u='https://t.me/olkadolka228';TG?.openTelegramLink?TG.openTelegramLink(u):location.href=u});
const telegramName=[user.first_name,user.last_name].filter(Boolean).join(' ');if($('#name')&&telegramName)$('#name').value=telegramName;
async function api(action,extra={}){if(!initData)throw new Error('Откройте O.nails через Telegram.');const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY},body:JSON.stringify({action,initData,...extra})});let d=null;try{d=await r.json()}catch{}if(!r.ok||!d?.ok)throw new Error(d?.error||'Ошибка сервера.');return d}
async function loadAvailability(){const d=await api('availability');state.booked=new Set((d.bookedDates||[]).map(String));renderCalendar()}
function renderCalendar(){const grid=$('#calendarGrid');if(!grid)return;const y=state.month.getFullYear(),m=state.month.getMonth();$('#calendarTitle').textContent=new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(state.month).replace(/^./,c=>c.toUpperCase());const first=new Date(y,m,1),offset=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),today=localISO();grid.innerHTML='';for(let i=0;i<offset;i++){const e=document.createElement('span');e.className='day empty';grid.appendChild(e)}for(let n=1;n<=days;n++){const d=new Date(y,m,n),iso=`${y}-${String(m+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`,b=document.createElement('button');b.type='button';b.className='day';b.textContent=n;const weekend=d.getDay()===0||d.getDay()===6,past=iso<today,busy=state.booked.has(iso);if(iso===today)b.classList.add('today');if(weekend)b.classList.add('weekend');else if(past)b.classList.add('past');else if(busy)b.classList.add('busy');else b.classList.add('free');if(state.selected===iso)b.classList.add('selected');b.disabled=weekend||past||busy;b.title=busy?'Дата уже занята':weekend?'Выходной':past?'Дата прошла':'';if(!b.disabled)b.addEventListener('click',()=>selectDate(iso));grid.appendChild(b)}$('#prevMonth').disabled=new Date(y,m,1)<new Date(new Date().getFullYear(),new Date().getMonth(),1);$('#nextMonth').disabled=false}
function selectDate(iso){state.selected=iso;$('#date').value=iso;$('#dateHint').textContent=`Выбрано: ${fmtDate(iso)} · время 16:00`;$('#dateHint').className='hint ok';renderCalendar()}
$('#prevMonth')?.addEventListener('click',()=>{if($('#prevMonth').disabled)return;state.month=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);renderCalendar()});$('#nextMonth')?.addEventListener('click',()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);renderCalendar()});
$('#designFile')?.addEventListener('change',e=>handleFile(e.target.files?.[0]));
function handleFile(file){if(!file){return}const allowed=['image/jpeg','image/png','image/webp'];if(!allowed.includes(file.type)){toast('Разрешены JPG, PNG и WEBP',true);eClearFile();return}if(file.size>10*1024*1024){toast('Файл должен быть не больше 10 МБ',true);eClearFile();return}state.file=file;const reader=new FileReader();reader.onload=()=>{state.fileData=reader.result;const p=$('#filePreview');p.classList.remove('hidden');p.innerHTML=`<img src="${state.fileData}" alt="Пример дизайна"><div><b>${esc(file.name)}</b><small>${(file.size/1024/1024).toFixed(2)} МБ</small></div><button type="button" class="file-remove" id="removeFile">×</button>`;$('#removeFile').addEventListener('click',eClearFile)};reader.readAsDataURL(file)}
function eClearFile(){state.file=null;state.fileData=null;if($('#designFile'))$('#designFile').value='';const p=$('#filePreview');if(p){p.classList.add('hidden');p.innerHTML=''}}
function bookingHtml(b){if(!b)return '<div class="loader">❌ Активная запись не найдена.</div>';const img=b.design_file_url?`<img class="booking-image" src="${esc(b.design_file_url)}" alt="Пример дизайна">`:'';return `<div class="booking-details"><div class="detail"><span>👤 Имя</span><b>${esc(b.name)}</b></div><div class="detail"><span>📅 Дата</span><b>${esc(fmtDate(b.booking_date))}</b></div><div class="detail"><span>🕐 Время</span><b>${esc(String(b.booking_time||'16:00').slice(0,5))}</b></div><div class="detail"><span>💅 Длина</span><b>${esc(b.nail_length)}</b></div><div class="detail"><span>🎨 Дизайн</span><b>${esc(b.design||'нет')}</b></div><div class="detail"><span>✂️ Снятие</span><b>${b.removal?'да':'нет'}</b></div><div class="detail"><span>🔧 Коррекция</span><b>${b.correction?'да':'нет'}</b></div><div class="detail"><span>💬 Комментарий</span><b>${esc(b.comment||'нет')}</b></div>${img}</div>`}
async function loadBooking(boxId,cancelMode=false,rescheduleMode=false){const box=$('#'+boxId);if(!box)return;box.innerHTML='<div class="loader">Загрузка…</div>';try{const d=await api('my_booking');if(!d.booking){box.innerHTML='<div class="loader">❌ Активная запись не найдена.</div>';return}box.innerHTML=bookingHtml(d.booking);if(cancelMode)box.innerHTML+=`<div class="actions"><button class="danger-btn" id="doCancel">× Отменить запись</button><button class="secondary" id="backHome">Назад</button></div>`;else if(rescheduleMode)renderReschedule(box,d.booking);else box.innerHTML+=`<div class="actions"><button class="secondary" id="toCancel">× Отменить</button><button class="secondary" id="toReschedule">↻ Перенести</button></div>`;$('#backHome')?.addEventListener('click',()=>go('home'));$('#toCancel')?.addEventListener('click',()=>go('cancel'));$('#toReschedule')?.addEventListener('click',()=>go('reschedule'));$('#doCancel')?.addEventListener('click',cancelBooking)}catch(e){box.innerHTML=`<div class="loader">❌ ${esc(e.message)}</div>`}}
async function cancelBooking(){if(!confirm('Отменить вашу запись?'))return;try{await api('cancel_booking');toast('Запись отменена');go('home')}catch(e){toast(e.message,true)}}
function renderReschedule(box,b){box.innerHTML=bookingHtml(b)+`<div class="form-card" style="margin-top:14px"><div class="field"><label>Новая дата</label><div class="calendar-card"><div class="calendar-head"><div></div><div><b>Выберите новую дату</b><small>только будни</small></div><div></div><div id="resCalendarGrid" class="calendar-grid"></div></div></div><button class="primary wide" id="doReschedule">↻ Перенести запись</button><div id="resStatus" class="status"></div></div>`;const input=document.createElement('input');input.type='hidden';input.id='rescheduleDate';box.appendChild(input);renderRescheduleCalendar(input);$('#doReschedule').addEventListener('click',async()=>{const date=input.value;if(!date){$('#resStatus').textContent='Выберите дату';$('#resStatus').className='status error';return}try{await api('reschedule_booking',{newDate:date});toast('Запись перенесена');go('mybooking')}catch(e){$('#resStatus').textContent=e.message;$('#resStatus').className='status error'}})}
function renderRescheduleCalendar(input){const g=$('#resCalendarGrid');if(!g)return;const base=new Date();for(let i=0;i<21;i++){const d=new Date(base.getFullYear(),base.getMonth(),base.getDate()+i),iso=localISO(d),b=document.createElement('button');b.type='button';b.className='day '+(d.getDay()===0||d.getDay()===6?'weekend':'free');b.textContent=d.getDate();b.disabled=d.getDay()===0||d.getDay()===6||state.booked.has(iso);if(state.booked.has(iso))b.classList.add('busy');if(!b.disabled)b.addEventListener('click',()=>{input.value=iso;g.querySelectorAll('.selected').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');});g.appendChild(b)}}
async function submitBooking(){const status=$('#bookingStatus'),date=$('#date')?.value,name=$('#name')?.value.trim();if(!name||!date){status.textContent='Заполните имя и выберите дату';status.className='status error';return}const d=new Date(date+'T00:00:00');if(d.getDay()===0||d.getDay()===6){status.textContent='Можно выбрать только будний день';status.className='status error';return}if(state.booked.has(date)){status.textContent='Эта дата уже занята';status.className='status error';return}const btn=$('#submitBooking');btn.disabled=true;btn.textContent='Проверяем…';status.textContent='';try{const payload={name,booking_date:date,booking_time:'16:00',nail_length:$('#length')?.value||'',design:$('#design')?.value.trim()||'',removal:Boolean($('#removal')?.checked),correction:Boolean($('#correction')?.checked),comment:$('#comment')?.value.trim()||''};if(state.fileData){payload.design_file={name:state.file.name,type:state.file.type,size:state.file.size,data:state.fileData.split(',')[1]}}const data=await api('create_booking',{booking:payload});$('#successText').textContent=`Ваша запись на ${fmtDate(data.booking.booking_date)} в ${String(data.booking.booking_time||'16:00').slice(0,5)} сохранена. До встречи в O.nails ♡`;go('success');toast('Запись подтверждена')}catch(e){status.textContent=e.message;status.className='status error';if(/занят/i.test(e.message))loadAvailability().catch(()=>{})}finally{btn.disabled=false;btn.textContent='Проверить запись →'}}
$('#submitBooking')?.addEventListener('click',submitBooking);
function toast(text,error=false){const el=$('#toast');if(!el)return;el.textContent=text;el.style.background=error?'#9d5366':'#3d252d';el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2300)}
renderCalendar();loadAvailability().catch(()=>{});
